export { RunningApp } from './running-app.view'
export { PlatformState, ChildApplicationAPI } from './platform.state'
export { PlatformBannerView } from './platform-banner.view'
export { PlatformSettingsStore, Executable } from './platform-settings'
export { PlatformView } from './platform.view'
export * from './installer'
export * from './favorites'
export { RequestsExecutor } from './requests-executot'
